name: Cherry Pick Commit

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name you want the cherry-pick branch to be based from'
        required: true
      commit_hash:
        description: 'Commit Hash'
        required: true
      PR_number:
        description: 'PR # Associated with Cherry Pick'
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test for Command Injection
        shell: bash
        run: |
          echo "Branch input is: ${{ github.event.inputs.branch_name }}"
          echo "Commit hash is: ${{ github.event.inputs.commit_hash }}"
          echo "PR number is: ${{ github.event.inputs.PR_number }}"
